# Generated by Django 5.1.7 on 2025-04-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='locked_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
