# Generated by Django 5.1.7 on 2025-04-02 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccounts', '0002_newuser_locked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
